version: '3.8'

services:
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_vol:/var/lib/mysql
    networks:
      - mynetwork

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq/
    networks:
      - mynetwork

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:1.25
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/www/html/api.lucasdbrito.com/:/var/www/html/api.lucasdbrito.com/
      - /etc/ssl:/etc/ssl
    networks:
      - mynetwork

volumes:
  mysql_vol:
    driver: local
  rabbitmq_vol:
    driver: local
networks:
  mynetwork:
    driver: bridge
